### ISSUE TITLE
建议不要提供书籍的下载链接

### ISSUE THREAD

**Issue by sanri** [0voice/Understanding_in_Rust#1]
提供书籍的下载链接, 是否经过了作者同意?

**Comment by zhengxingjian** [comment]
可以提供样章，和推荐心得，电子书直接放链接不合适，影响太大了，而且其它资料搜集归整的挺好的，这会让这个仓库更火，所以建议不要放链接，知道你是好心，推广rust。

**Comment by floydawong** [comment]
> 可以提供样章，和推荐心得，电子书直接放链接不合适，影响太大了，而且其它资料搜集归整的挺好的，这会让这个仓库更火，所以建议不要放链接，知道你是好心，推广rust。

你有本事盗取别人的文章, 你有本事自己写啊
