### ISSUE TITLE
请停止你的侵权行为！

### ISSUE THREAD

**Issue by ZhangHanDong** [0voice/Understanding_in_Rust#2]
我是《Rust 编程之道》的作者，以及 《Rust Magazine》的编辑，现在给你一个善意的警告：请马上删除你提供的盗版书籍pdf下载资料，并且把转载自 《Rust Magazine》的文章添加原文出处！你现在的做法是违法行为！

我也很尊重你的工作，整理一份学习资料 Rust 社区也很欢迎。但你要注意版权意识。

如果不听劝，那就只能选择法律手段了。

谢谢合作！ @wangbojing  @wenchao1024

**Comment by ZhangHanDong** [comment]
我这里有你的资料，谢谢！请不要以为危言耸听。

![Screen Shot 2021-09-08 at 12 05 25](https://user-images.githubusercontent.com/27893/132444820-a90d4215-102d-4a54-85e1-1c215190ff68.png)

**Comment by ZhangHanDong** [comment]
国内出版的所有有版权的书，不仅仅是我那一本，你都应该撤下下载链接，甚至都不能有云盘存储，否则那都是你侵权证据！ @wangbojing @wenchao1024 

另外，转载文章也加上出处！ 包括里面华为、蚂蚁、个人的文章，虽然免费但都是有版权的。

望自重！

**Comment by wenchao1024** [comment]
已处理。
